services:
  db:
    image: pgvector/pgvector:pg16
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/setup.sql:/docker-entrypoint-initdb.d/1-setup.sql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/2-schema.sql

volumes:
  pgdata:

